export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import {
  MantineProvider,
  createTheme,
  MantineColorsTuple,
  ColorSchemeScript,
} from "@mantine/core";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <MantineProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </MantineProvider>
  );
}
